//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCalculaBonificacao.WSSalarioNoCSharp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WSSalarioNoCSharp.WSSalario")]
    public interface WSSalario {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSSalario/salarioRequest", ReplyAction="http://ws/WSSalario/salarioResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSCalculaBonificacao.WSSalarioNoCSharp.salarioResponse salario(WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSSalario/salarioRequest", ReplyAction="http://ws/WSSalario/salarioResponse")]
        System.Threading.Tasks.Task<WSCalculaBonificacao.WSSalarioNoCSharp.salarioResponse> salarioAsync(WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="salario", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class salarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double salario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int qtdFaltas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int qtdAdvertencias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int produtividade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int qtdHorasCursos;
        
        public salarioRequest() {
        }
        
        public salarioRequest(double salario, int qtdFaltas, int qtdAdvertencias, int produtividade, int qtdHorasCursos) {
            this.salario = salario;
            this.qtdFaltas = qtdFaltas;
            this.qtdAdvertencias = qtdAdvertencias;
            this.produtividade = produtividade;
            this.qtdHorasCursos = qtdHorasCursos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="salarioResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class salarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public salarioResponse() {
        }
        
        public salarioResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSalarioChannel : WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSalarioClient : System.ServiceModel.ClientBase<WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario>, WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario {
        
        public WSSalarioClient() {
        }
        
        public WSSalarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSalarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSalarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSalarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSCalculaBonificacao.WSSalarioNoCSharp.salarioResponse WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario.salario(WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest request) {
            return base.Channel.salario(request);
        }
        
        public double salario(double salario1, int qtdFaltas, int qtdAdvertencias, int produtividade, int qtdHorasCursos) {
            WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest inValue = new WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest();
            inValue.salario = salario1;
            inValue.qtdFaltas = qtdFaltas;
            inValue.qtdAdvertencias = qtdAdvertencias;
            inValue.produtividade = produtividade;
            inValue.qtdHorasCursos = qtdHorasCursos;
            WSCalculaBonificacao.WSSalarioNoCSharp.salarioResponse retVal = ((WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario)(this)).salario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCalculaBonificacao.WSSalarioNoCSharp.salarioResponse> WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario.salarioAsync(WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest request) {
            return base.Channel.salarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCalculaBonificacao.WSSalarioNoCSharp.salarioResponse> salarioAsync(double salario, int qtdFaltas, int qtdAdvertencias, int produtividade, int qtdHorasCursos) {
            WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest inValue = new WSCalculaBonificacao.WSSalarioNoCSharp.salarioRequest();
            inValue.salario = salario;
            inValue.qtdFaltas = qtdFaltas;
            inValue.qtdAdvertencias = qtdAdvertencias;
            inValue.produtividade = produtividade;
            inValue.qtdHorasCursos = qtdHorasCursos;
            return ((WSCalculaBonificacao.WSSalarioNoCSharp.WSSalario)(this)).salarioAsync(inValue);
        }
    }
}
